### ISSUE TITLE
Code release data

### ISSUE THREAD

**Issue by luffycodes** [peterwestai2/symbolic-knowledge-distillation#1]
Hello, 

Thanks for such an exciting paper !

I was wondering when the code will be released, if there is a tentative date?

Thanks !

**Comment by peterwestuw** [comment]
Thank you for the interest! We are currently deciding on the best release strategy, to adhere to policies for work under submission. We may communicate individually with researchers to share our code until the submission is fully reviewed. Please email the first author if you are interested in a private release! 

We are expecting to have an initial version of this code together in the next few weeks.

**Comment by superchargez** [comment]
Can the model be used like huggingface models for zero shot language tasks? Would love to have a notebook performing various tasks (or perhaps several separate ones a notebook for each task).

**Comment by peterwestai2** [comment]
Sorry for the very late reply! We are planning to release the code soon, which will likely include notebooks for each step

**Comment by peterwestai2** [comment]
We have now released notebooks for various aspects of the work. Specifically, for generating events + inferences, and for generating with COMET-DISTIL models. We describe these in the "Quick Start" section of the readme. If this does not cover everything, please reopen the issue and we can work on including any desired functionality!
