### ISSUE TITLE
Instruction of Input format

### ISSUE THREAD

**Issue by XingLuxi** [peterwestai2/symbolic-knowledge-distillation#2]
Hi, 
What is the input format of the COMET^{distil}, such as, position of special tokens ?
Will you give an instruction of how to construct the input to correctly use the COMET^{distill} model?

Thanks.

**Comment by peterwestuw** [comment]
Hi! 

We are currently constructing a full guide for code use, and figuring out policies for major changes to this repo under submission anonymity guidelines. 

For now, you can use the following code snippet to interface with the COMET^{distill} versions we include:

```
from transformers import GPT2Tokenizer, GPT2LMHeadModel
import torch
tokenizer = GPT2Tokenizer.from_pretrained('comet_distil_tokenizer/')
model = GPT2LMHeadModel.from_pretrained('comet_distil_low')

inp = tokenizer("<head> PersonX eats less </head> <relation> xEffect </relation> [GEN] ")['input_ids']
tokenizer.decode(model.generate(torch.tensor(inp).view(1,-1)).tolist()[0])
```

Using the files available from the link in the repo. You must also rename tokenizer_config to config in the tokenizer directory. Please let me know if this works for you!

**Comment by XingLuxi** [comment]
Thanks for your detailed reply!

That's very useful instruction.

I'm particularly concerned about the input format as the input largely influences the performance of PLMs. 
Slightly changes will lead to the different decoded results.

I have to say, this paper is really impressed! I am very interested in this work, and the proposed framework is of great value and really insightful to the research of PLMs and commonsense reasoning.

Looking forward to the further updating of this repo. And hoping to see more COMET-related interesting research!
