### ISSUE TITLE
Access to the Atomic10X

### ISSUE THREAD

**Issue by marcos0318** [peterwestai2/symbolic-knowledge-distillation#3]
Hi,  thank you for sharing your ideas and data! 

However, when I open the link you have provided on the google cloud, I found that the  ATOMIC10X.jsonl file does not have open access. It seems that the data cannot be directly downloaded.

I was wondering if the data is available for download now?

Best

**Comment by jmhessel** [comment]
Hi @marcos0318 

We are working on updating this repo, but for now, you should be able to access that file here:

https://storage.googleapis.com/ai2-mosaic-public/projects/symbolic-knowledge-decoding/ATOMIC10X.jsonl

Jack

**Comment by peterwestai2** [comment]
I believe this is resolved now (see readme)
