### ISSUE TITLE
How to find seed_events.txt?

### ISSUE THREAD

**Issue by wanicca** [peterwestai2/symbolic-knowledge-distillation#6]
Hello, I saw this in the README.

> Run through generate_event.ipynb one block at a time. Instructions are included there. You will need a set of seed events which are used for few shot prompting. We provide such a file but you can substitute in your own, depending on the application.

It said the file is provided. However, I cannot find the seed_events file in the data. Can you provide it in this repo?

**Comment by peterwestai2** [comment]
Sorry to have missed this, we just added `seed_events.txt` to the repo. Let us know if you run into any other issues!
